### ISSUE TITLE
POST returns error message "string indices must be integers"

### ISSUE THREAD

**Issue by marija185** [iml130/firos#7]
Hi Dominik,
this issue is maybe specific to the structure of the message. In the previous version of firos POST worked with this topic but now it says the error and the topic is not received. Maybe you will have a quick solution.
This is the output in terminal running the firos:
```
Serving HTTP on 0.0.0.0 port 10100 ...
----------------------------------------
Exception happened during processing of request from ('192.168.208.4', 39880)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in _init_
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/root/catkin_ws/src/firos/firos/include/server/requestHandler.py", line 68, in do_POST
    action["action"](self, action)
  File "/root/catkin_ws/src/firos/firos/include/server/requestHandler.py", line 128, in requestFromCB
    dataStruct = buildTypeStruct(data[topic])
  File "/root/catkin_ws/src/firos/firos/include/server/requestHandler.py", line 156, in buildTypeStruct
    if 'type' in objval[k] and 'value' in objval[k] and objval[k]['type'] == 'array': # Check if we got an Array-Type value
TypeError: string indices must be integers
----------------------------------------
```
and also this message of orion:
```
orion_1  | time=Wednesday 27 Feb 13:37:31 2019.916Z | lvl=WARN | corr=d5451f84-3a94-11e9-868e-0242ac130003 | trans=1551274480-610-00000000144 | from=172.19.0.1 | srv=<default> | subsrv=<default> | comp=Orion | op=AlarmManager.cpp[432]:badInputReset | msg=Releasing alarm BadInput 172.19.0.1
orion_1  | time=Wednesday 27 Feb 13:37:31 2019.920Z | lvl=WARN | corr=N/A | trans=1551274480-610-00000000145 | from=pending | srv=pending | subsrv=pending | comp=Orion | op=AlarmManager.cpp[328]:notificationError | msg=Raising alarm NotificationError http://172.19.0.2:10100/firos: (curl_easy_perform failed: Server returned nothing (no headers, no data))
```
and it is a result of making a POST in Postman:
```
{"contextElements": [{"attributes": [{"type": "COMMAND", "name": "COMMAND", "value": ["motion_channel"]}, {"type": "opil_v1.msg.MotionAssignment", "name": "motion_channel", "value": "{%27is_waypoint%27: false, %27task_id%27: {%27id%27: 1, %27description%27: %27%27}, %27point%27: {%27y%27: 13.85, %27x%27: 4.0, %27theta%27: 0.0}, %27point_id%27: {%27id%27: 1, %27description%27: %27%27}, %27sequence%27: {%27length%27: 2, %27sequence_number%27:1}, %27motion_area%27: {%27header%27: {%27stamp%27: {%27secs%27: 0, %27nsecs%27: 0}, %27frame_id%27: %27%27, %27seq%27: 0}, %27polygon%27: {%27points%27: []}}, %27max_velocity%27: {%27linear%27: {%27y%27: 0.0, %27x%27: 0.0, %27z%27: 0.0}, %27angular%27: {%27y%27: 0.0, %27x%27: 0.0, %27z%27: 0.0}}, %27header%27: {%27stamp%27: {%27secs%27: 1536222372, %27nsecs%27: 930678771}, %27frame_id%27: %27/map%27, %27seq%27: 0}, %27max_acceleration%27: {%27linear%27: {%27y%27: 0.0, %27x%27: 0.0, %27z%27: 0.0}, %27angular%27: {%27y%27: 0.0, %27x%27: 0.0, %27z%27: 0.0}}, %27motion_id%27: {%27id%27: 1, %27description%27: %27%27}, %27robot_id%27: {%27id%27: 0, %27description%27: %27%27}, %27use_orientation%27: true}"}], "type": "ROBOT", "id": "robot_opil_v1", "isPattern": "false"}], "updateAction": "APPEND"}
```
In Firefox I can see this:
```
    "motion_channel": {
      "type": "opil_v1.msg.MotionAssignment",
      "value": "{%27is_waypoint%27: false, %27task_id%27: {%27id%27: 1, %27description%27: %27%27}, %27point%27: {%27y%27: 13.85, %27x%27: 4.0, %27theta%27: 0.0}, %27point_id%27: {%27id%27: 1, %27description%27: %27%27}, %27sequence%27: {%27length%27: 2, %27sequence_number%27:1}, %27motion_area%27: {%27header%27: {%27stamp%27: {%27secs%27: 0, %27nsecs%27: 0}, %27frame_id%27: %27%27, %27seq%27: 0}, %27polygon%27: {%27points%27: []}}, %27max_velocity%27: {%27linear%27: {%27y%27: 0.0, %27x%27: 0.0, %27z%27: 0.0}, %27angular%27: {%27y%27: 0.0, %27x%27: 0.0, %27z%27: 0.0}}, %27header%27: {%27stamp%27: {%27secs%27: 1536222372, %27nsecs%27: 930678771}, %27frame_id%27: %27/map%27, %27seq%27: 0}, %27max_acceleration%27: {%27linear%27: {%27y%27: 0.0, %27x%27: 0.0, %27z%27: 0.0}, %27angular%27: {%27y%27: 0.0, %27x%27: 0.0, %27z%27: 0.0}}, %27motion_id%27: {%27id%27: 1, %27description%27: %27%27}, %27robot_id%27: {%27id%27: 0, %27description%27: %27%27}, %27use_orientation%27: true}",
      "metadata": {}
    },
```

**Comment by marija185** [comment]
Solved by POLIMI.
